[pytest]
log_cli = true
log_cli_level = DEBUG
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

# Add current directory to the Python path
pythonpath = .

# asyncio mode
asyncio_mode = auto

# Test paths (optional, but good practice)
testpaths = tests

# Add markers here if needed
markers =
    e2e: mark test as end-to-end.
    integration: mark test as integration test.
    performance: mark test as performance test.
    unit: mark test as unit test.

# Filter warnings (optional)
filterwarnings =
    # Ignore specific warnings if needed
    # ignore::DeprecationWarning

python_files = test_*.py
python_classes = Test*
python_functions = test_* 