# Script to run the EverRaise application (backend and frontend)
param(
    [switch]$Debug = $false,
    [int]$BackendPort = 0, # 0 means use the default from config
    [int]$FrontendPort = 0 # 0 means use the default from config
)

# Set error action preference
$ErrorActionPreference = "Stop"

# Get the root directory of the project (parent of the scripts directory)
$RootDir = Split-Path -Parent $PSScriptRoot 
$ScriptDir = $PSScriptRoot

# Import shared configuration
Import-Module "$ScriptDir\config.psm1" -Force

# Determine port numbers
if ($BackendPort -eq 0) {
    $BackendPort = Get-BackendPort
}
if ($FrontendPort -eq 0) {
    $FrontendPort = Get-FrontendPort
}

# Define paths
$BackendDir = Join-Path $RootDir "backend"
$FrontendDir = Join-Path $RootDir "frontend"

Write-Host "EverRaise Configuration:" -ForegroundColor Cyan
Write-Host "  Backend Port: $BackendPort" -ForegroundColor Cyan
Write-Host "  Frontend Port: $FrontendPort" -ForegroundColor Cyan

# Verify directories exist
if (-not (Test-Path $BackendDir)) {
    Write-Host "Backend directory not found at $BackendDir" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path $FrontendDir)) {
    Write-Host "Frontend directory not found at $FrontendDir" -ForegroundColor Red
    exit 1
}

# Force clear backend port
try {
    $connections = Get-NetTCPConnection -LocalPort $BackendPort -ErrorAction SilentlyContinue
    if ($connections) {
        Write-Host "Port $BackendPort is in use. Attempting to forcefully terminate processes..." -ForegroundColor Yellow
        
        foreach ($conn in $connections) {
            $process = Get-Process -Id $conn.OwningProcess -ErrorAction SilentlyContinue
            if ($process) {
                Write-Host "Forcefully terminating $($process.ProcessName) (PID: $($process.Id))..." -ForegroundColor Yellow
                Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
            }
        }
    }
} catch {
    $errorMessage = $_.Exception.Message
    Write-Host "Error checking port $BackendPort`: $errorMessage" -ForegroundColor Yellow
}

# Create .env file for frontend with correct backend URL
$frontendEnvFile = Join-Path $FrontendDir ".env.local"
Write-Host "Creating frontend environment file at $frontendEnvFile" -ForegroundColor Cyan
$envContent = @"
# Auto-generated by EverRaise startup script
VITE_API_URL=http://localhost:{0}
"@ -f $BackendPort
Set-Content -Path $frontendEnvFile -Value $envContent -Force

# Start the backend in a new window
Write-Host "Starting backend server in a new window..." -ForegroundColor Cyan
$backendArgs = "-NoProfile -ExecutionPolicy Bypass -File `"$ScriptDir\start-backend.ps1`" -Port $BackendPort"
if ($Debug) {
    $backendArgs += " -Debug"
}
Start-Process powershell.exe -ArgumentList $backendArgs -WindowStyle Normal

# Wait a moment for backend to initialize
Start-Sleep -Seconds 3

# Start the frontend in a new window
Write-Host "Starting frontend server in a new window..." -ForegroundColor Cyan
$frontendArgs = "-NoProfile -ExecutionPolicy Bypass -File `"$ScriptDir\start-frontend.ps1`""
Start-Process powershell.exe -ArgumentList $frontendArgs -WindowStyle Normal

Write-Host "Started EverRaise application!" -ForegroundColor Green
Write-Host "Backend is running at: http://localhost:$BackendPort" -ForegroundColor Cyan
Write-Host "Frontend is running at: http://localhost:$FrontendPort" -ForegroundColor Cyan
Write-Host "Close the terminal windows when you're done." -ForegroundColor Yellow 